/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquiposIndexRouteImport } from './routes/equipos.index'
import { Route as EquiposIdRouteImport } from './routes/equipos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposIndexRoute = EquiposIndexRouteImport.update({
  id: '/equipos/',
  path: '/equipos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposIdRoute = EquiposIdRouteImport.update({
  id: '/equipos/$id',
  path: '/equipos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipos/$id': typeof EquiposIdRoute
  '/equipos/': typeof EquiposIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipos/$id': typeof EquiposIdRoute
  '/equipos': typeof EquiposIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipos/$id': typeof EquiposIdRoute
  '/equipos/': typeof EquiposIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipos/$id' | '/equipos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipos/$id' | '/equipos'
  id: '__root__' | '/' | '/equipos/$id' | '/equipos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquiposIdRoute: typeof EquiposIdRoute
  EquiposIndexRoute: typeof EquiposIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/': {
      id: '/equipos/'
      path: '/equipos'
      fullPath: '/equipos/'
      preLoaderRoute: typeof EquiposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos/$id': {
      id: '/equipos/$id'
      path: '/equipos/$id'
      fullPath: '/equipos/$id'
      preLoaderRoute: typeof EquiposIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquiposIdRoute: EquiposIdRoute,
  EquiposIndexRoute: EquiposIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
